// 图书优惠策略
package book.discount;
// 引入项目
import com.lyy.entity.Order;

dialect  "mvel"

// 规则一:所购图书总价在100元以下的没有优惠
rule "book_discount_1"
    when
        $order:Order(originalPrice < 100)   // 模式匹配，到规则引擎(工作内存)查找Order对象
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.println("没有优惠");
end


// 规则二:所购图书总价在100元-200元之间，优惠20元
rule "book_discount_2"
    when
        $order:Order(originalPrice >= 100 && originalPrice < 200)
    then
        $order.setRealPrice($order.getOriginalPrice() - 20);
        System.out.println("优惠20");
end


// 规则三:所购图书总价在200元-300元之间，优惠50元
rule "book_discount_3"
    when
        $order:Order(originalPrice >= 200 && originalPrice < 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 50);
        System.out.println("优惠50");
end


// 规则四:所购图书总价在300元以上，优惠100元
rule "book_discount_4"
    when
        // 模式匹配，到规则引擎(工作内存)查找Order对象
        $order:Order(originalPrice >= 300)
    then
        $order.setRealPrice($order.getOriginalPrice() - 100);
        System.out.println("优惠100");
end